### ISSUE TITLE
Flood gate

### ISSUE THREAD

**Issue by wi-ta** [BuildCraft/BuildCraft-Localization#272]
Sorry but i fail with the Forums so this is the only place for me.

The translation for the flood gate is in German "Schleusentor" this is misleading and a word for word translation.

See the Duden please:
http://www.duden.de/rechtschreibung/Schleusentor
and a pic
http://www.duden.de/_media_/full/S/Schleusentor-201020591713.jpg

Please change in "Bereichfluter" or "Fluter"

**Comment by Adaptivity** [comment]
Ping @Vexatos

**Comment by Vexatos** [comment]
The issue is, "Fluter" is not really a word that exists. The correct translation for "Flood Gate" is "Schleusentor", even if it doesn't make much sense. I am unable to find a better translation, unfortunately.

**Comment by wi-ta** [comment]
Nevermind
If you not speak native german and if you have no technical education in german you can not understand.
Thank you you can close this

**Comment by peddermaster2** [comment]
​I know, I'm a bit late, but I am a German.

"Schleusentor" is in any case the worng word.
"Fluter" is a word creation for "fluten" (verb).
How about "Auslass" [Duden] (http://www.duden.de/rechtschreibung/Auslass).
It would fit the usage of the "flood gate".

**Comment by Vexatos** [comment]
"Auslass" is quite a decent word, I guess. I'll change it.
