### ISSUE TITLE
Russian translation for 7.1.15

### ISSUE THREAD

**Issue by lex1975** [BuildCraft/BuildCraft-Localization#288]
I added a Russian translation in the latest version. And there are three changes in the translation. Changelog is attached.
[buildcraft-7.1.15_changes.txt](https://github.com/BuildCraft/BuildCraft-Localization/files/180187/buildcraft-7.1.15_changes.txt)
[ru_RU.zip](https://github.com/BuildCraft/BuildCraft-Localization/files/180186/ru_RU.zip)

**Comment by Vierkantor** [comment]
Thanks for the translation! I [committed it](https://github.com/BuildCraft/BuildCraft-Localization/commit/78e87a0d54a1794ff45a4a4a5699797f784bf90d) for you, but if you want to, I would like a pull request next time :)
