### ISSUE TITLE
A branch for 8.0.x?

### ISSUE THREAD

**Issue by 3TUSK** [BuildCraft/BuildCraft-Localization#293]
Per title said, since 8.0.x has had some alpha builds (with version number being as 7.99.x), is there any chance to allow localization for 8.0.x branch to be started, so that it can be done before a release build is ready to go?

**Comment by AlexIIL** [comment]
Not yet - currently the plan is to finish all content (most likely except for all of the guide book), and then move from alpha to beta. At that point I'll open up translations, because then I won't be adding and removing language keys.

**Comment by 3TUSK** [comment]
Closing it - apparently the question has been answered.
